### ISSUE TITLE
Manage substitute - not there?

### ISSUE THREAD

**Issue by mts2605** [SAP-samples/teched2020-DEV264#1]
Hi Venugopal/experts
How come, when doing the steps in excersise 2, i can not see "Manage My Substitutes"?
Missing role, or anything else missing in my account?

Great work with this session/manual! Thanks.

Michael

**Comment by ArchanaShukla** [comment]
Hello Michael,
Can you confirm if you are you inside the My Inbox application and then clicking on the User icon ?

**Comment by mts2605** [comment]
Hi Archana
Thanks a lot, must admit that I was in the SCP WF cockpit. When in the "Inbox" the Manage substitutes is there;-)
Best regards,
Michael
