### ISSUE TITLE
Authorities : Documentation

### ISSUE THREAD

**Issue by srinivasnrao** [SAP-samples/teched2020-DEV264#3]
Hi Team - I tried to find the documentation for the different "authorities" that we put as "Configuration parameter" during workflow service instance creation, but could not find it. I am sure I am just looking at the wrong places. 

Can you please give me the link to the official documentation for it?

Thanks & Regards
Srinivas Rao.

**Comment by srinivasnrao** [comment]
@venugopalchembrakalathil @rich-heilman  - Could you please help me to understand ?

**Comment by ArchanaShukla** [comment]
Hello @srinivasnrao,
All the needed authorities/scope are provided with respective APIs depending upon what you want to achieve. 
https://api.sap.com/api/SAP_CP_Workflow_CF/resource

![image](https://user-images.githubusercontent.com/34297037/103769890-2052d200-504b-11eb-9a06-0a0749e56566.png)


[documentation link 1](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/103f2b307af142e5a91368c1539dea57.html?q=authorities)

[documentation link 2](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/c74f5ff9065b4baeb700d033602ef1d9.html?q=authorities)

**Comment by srinivasnrao** [comment]
Thanks @ArchanaShukla. This helps! 👍

**Comment by srinivasnrao** [comment]
Thanks @ArchanaShukla. This helps ! 👍
